# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [10]:
# Import torch
import torch

# Create random tensor
x = torch.rand(3, 3)
print(x)


tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [11]:
# Create another random tensor
y = torch.rand(3, 3)

# Perform matrix multiplication 
z = torch.matmul(x, y)
print(z)


tensor([[0.5105, 0.5210, 1.0262],
        [0.5604, 0.9138, 0.9725],
        [0.5657, 0.6870, 1.0581]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [12]:
# Set manual seed
torch.manual_seed(42)

# Create two random tensors
a = torch.rand(2, 3)
b = torch.rand(3, 2)

# Matrix multiply tensors
c = torch.matmul(a, b)
print("Result of a @ b:\n", c)


Result of a @ b:
 tensor([[1.4450, 1.0493],
        [1.1750, 1.1700]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [13]:
# Set random seed on the GPU
if torch.cuda.is_available():
    torch.cuda.manual_seed(42)
    print("GPU seed set to 42")
else:
    print("No GPU available.")


No GPU available.



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [14]:
# Set random seed
torch.manual_seed(42)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

# Create two random tensors on GPU (if available)
tensor_A = torch.rand(3, 3, device=device)
tensor_B = torch.rand(3, 3, device=device)
print("Tensor A:\n", tensor_A)
print("Tensor B:\n", tensor_B)


Using device: cpu
Tensor A:
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
Tensor B:
 tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [15]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(tensor_A, tensor_B)
print("Result of matmul (A @ B):\n", result)


Result of matmul (A @ B):
 tensor([[1.0774, 1.6830, 1.4215],
        [0.7253, 1.6503, 1.2036],
        [1.1281, 1.5234, 1.2804]])


### 8. Find the maximum and minimum values of the output of 7.

In [16]:
# Find max
max_value = torch.max(result)
print("Maximum value:", max_value.item())

# Find min
min_value = torch.min(result)
print("Minimum value:", min_value.item())


Maximum value: 1.6830329895019531
Minimum value: 0.7252506017684937


### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
arg_max = torch.argmax(result)
print("Index of max value:", arg_max.item())

# Find arg min
arg_min = torch.argmin(result)
print("Index of min value:", arg_min.item())


Index of max value: 1
Index of min value: 3



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed
torch.manual_seed(42)

# Create random tensor
x = torch.rand(1, 3, 1, 3)
print("Original tensor (x):\n", x)
print("Shape before squeeze:", x.shape)

# Remove single dimensions
y = x.squeeze()

# Print out tensors and their shapes
print("Tensor after squeeze (y):\n", y)
print("Shape after squeeze:", y.shape)


Original tensor (x):
 tensor([[[[0.8823, 0.9150, 0.3829]],

         [[0.9593, 0.3904, 0.6009]],

         [[0.2566, 0.7936, 0.9408]]]])
Shape before squeeze: torch.Size([1, 3, 1, 3])
Tensor after squeeze (y):
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
Shape after squeeze: torch.Size([3, 3])
